### ISSUE TITLE
Sending requests with manually-defined parameters is ignoring zyte_api meta parameter

### ISSUE THREAD

**Issue by ogiaquino** [scrapy-plugins/scrapy-zyte-api#107]
I tried using this feature [Sending requests with manually-defined parameters](https://github.com/scrapy-plugins/scrapy-zyte-api/tree/main#sending-requests-with-manually-defined-parameters) and combine with scrapy-poet integration but it seems that scrapy_zyte_api.providers.ZyteApiProvider is ignoring **zyte_api** parameter from my spider request object

https://github.com/scrapy-plugins/scrapy-zyte-api/blob/main/scrapy_zyte_api/providers.py#L75-L88

```
        zyte_api_meta = {}
        if html_requested:
            zyte_api_meta["browserHtml"] = True
        for item_type, kw in item_keywords.items():
            if item_type in to_provide:
                zyte_api_meta[kw] = True
        api_request = Request(
            url=request.url,
            meta={
                "zyte_api": zyte_api_meta,
                "zyte_api_default_params": False,
            },
            callback=NO_CALLBACK,
        )
```

Is it possible to change this [zyte_api_meta = {}](https://github.com/scrapy-plugins/scrapy-zyte-api/blob/main/scrapy_zyte_api/providers.py#L75) to `zyte_api_meta = request.meta.get('zyte_api', {})`

**Comment by kmike** [comment]
Hey @ogiaquino! Do you have a basic code example? I'm not sure I understand the use case.

**Comment by ogiaquino** [comment]
Hi @kmike we are using 'SCRAPY_POET_PROVIDERS' : {"scrapy_zyte_api.providers.ZyteApiProvider": 500}, to send parameters to Zyte API. But looking into this https://github.com/scrapy-plugins/scrapy-zyte-api/blob/main/scrapy_zyte_api/providers.py#L75-L88 it is not really getting any key/values from request.meta or maybe we are doing it wrong? 

The [api request](https://github.com/scrapy-plugins/scrapy-zyte-api/blob/main/scrapy_zyte_api/providers.py#L81) is just consuming [zyte_api_meta](https://github.com/scrapy-plugins/scrapy-zyte-api/blob/main/scrapy_zyte_api/providers.py#L84) but totally ignoring request.meta received by [__call__](https://github.com/scrapy-plugins/scrapy-zyte-api/blob/main/scrapy_zyte_api/providers.py#L51) therefore ignoring the meta set at the request in the spider level.

```
import scrapy

class SampleQuotesSpider(scrapy.Spider):
    name = "sample_quotes"

   custom_settings = {
        'DOWNLOADER_MIDDLEWARES' : {
            "scrapy_poet.InjectionMiddleware": 543,
            "scrapy_zyte_api.ScrapyZyteAPIDownloaderMiddleware": 1000,
        },
        'SCRAPY_POET_PROVIDERS' : {"scrapy_zyte_api.providers.ZyteApiProvider": 500},
    }

    def start_requests(self):
        yield scrapy.Request(
            url="https://quotes.toscrape.com/",
            meta={
                "zyte_api": {
                    "browserHtml": True,
                    "actions": [
                        {
                            "action": "waitForSelector",
                            "selector": {
                                "type": "css",
                                "value": ".product-details",}
                        },
                    ]
                }
            },
        )

    def parse(self, response):
        print(response.text)
        # "<html>…</html>"
```

**Comment by ogiaquino** [comment]
It's in the sample 

        'SCRAPY_POET_PROVIDERS' : {"scrapy_zyte_api.providers.ZyteApiProvider": 500},

**Comment by kmike** [comment]
I mean in the spider itself the provider is not used. Is it something like `def parse(self, response, product: Product):` ?

**Comment by kmike** [comment]
My concern is the following: 

> def parse(self, response, product: Product)

Currently zyte_api meta key controls what you get in `response`, and the provider creates a request to populate `product`. Currently it'd be 2 separate Zyte API requests (which is a separate issue). Using zyte_api paramaters in the provider can lead to issues. For example, here the second API request would use browserHtml: true unnecessarily. It may also break the Zyte API request - e.g. you wanted httpResponseBody in the `response`, but httpResponseBody is not compatible yet with product: true.

**Comment by kmike** [comment]
It seems a better way is to provide more dependencies, like Actions. I've started a draft here: https://github.com/scrapy-plugins/scrapy-zyte-api/pull/110; it's not finished yet.

**Comment by Gallaecio** [comment]
There’s [`ZYTE_API_PROVIDER_PARAMS`](https://scrapy-zyte-api.readthedocs.io/en/latest/reference/settings.html#zyte-api-provider-params) for spider-wide parameters for provider requests. Would that be enough, or should we implement a `zyte_api_provider` meta  key accordingly?
