### ISSUE TITLE
Scrapy errors due to decompression attempt based on Content-Encoding

### ISSUE THREAD

**Issue by BurnzZ** [scrapy-plugins/scrapy-zyte-api#11]
For Zyte API requests with `httpResponseHeader=True`, some websites would return headers like `Content-Encoding: gzip`. 

In the current setup, all of the headers in the `httpResponseHeader` from Zyte API response is used to create the Response in the Download Handler.

Now, when the response containing the `Content-Encoding: gzip` header is processed by the Downloader Middlewares, the `scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware` errors out since it's attempting to decompress the gzipped response.

This is not the case since Zyte API already decompressed the contents.

**Comment by BurnzZ** [comment]
Closing this as https://github.com/scrapy-plugins/scrapy-zyte-api/pull/14 has been merged. However, it won't be merged to `master` until https://github.com/scrapy-plugins/scrapy-zyte-api/pull/10 is merged as well

**Comment by kmike** [comment]
This is fixed now.
