### ISSUE TITLE
A way to limit the Zyte API requests

### ISSUE THREAD

**Issue by BurnzZ** [scrapy-plugins/scrapy-zyte-api#111]
I'm thinking of a feature where the user can indicate the max number of Zyte API requests for a given spider crawl. When this number is reached, the spider shuts down.

The main use case for this is to limit the costs per crawl.

**Comment by Gallaecio** [comment]
Wouldn’t [CLOSESPIDER_PAGECOUNT](https://doc.scrapy.org/en/latest/topics/extensions.html#closespider-pagecount) do the job in most cases?

**Comment by BurnzZ** [comment]
Yes, that's right. But it would also include non-ZAPI requests to the count.

**Comment by BurnzZ** [comment]
An alternative: https://github.com/croqaz/scrapy-count-filter

**Comment by BurnzZ** [comment]
Closing as https://github.com/scrapy-plugins/scrapy-zyte-api/pull/114 has been merged
