### ISSUE TITLE
Some discrepancies in request/response stats

### ISSUE THREAD

**Issue by BurnzZ** [scrapy-plugins/scrapy-zyte-api#112]
Starting on `scrapy-zyte-api >= 0.9.0`, we're now able request for item extraction in Zyte API directly in the spider:

```python
import scrapy
from scrapy_poet import DummyResponse
from zyte_common_items import Product


class SampleSpider(scrapy.Spider):
    name = "sample"

    def start_requests(self):
        yield scrapy.Request(
            "http://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html",
            self.parse_product,
        )

    def parse_product(
        self,
        response: DummyResponse,
        product: Product,
    ):
        yield product
```

In the Scrapy crawl stats, we have these:
```
{
 ...
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'response_received_count': 2,
 'scrapy-zyte-api/attempts': 1,
 'scrapy-zyte-api/status_codes/200': 1,
 'scrapy-zyte-api/success': 1,
 'scrapy_poet/dummy_response_count': 1,
 ...
}
```

These are kind of correct since `DummyResponse` is technically a response so our spider would have received 2 responses (i.e. `DummyResponse` and `Product`). Although I'd probably prefer to have a new `downloader/dummy_response_count` stat in lieu of the existing `scrapy_poet/dummy_response_count` just so that they are closer to one another _(which helps when visually inspecting them)_:

```
{
 ...
 'downloader/dummy_response_count': 1,
 'downloader/response_count': 2,
 ...
}
```

Another discrepancy is in **Scrapy Cloud** since it would appear that we have 2 requests:

<img width="766" alt="image" src="https://github.com/scrapy-plugins/scrapy-zyte-api/assets/3449761/ae58d05b-df1f-4ffc-a445-36e990738bb7">

It's because of `scrapinghub-entrypoint-scrapy.sh_scrapy.HubstorageDownloaderMiddleware` ([ref](https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/blob/master/sh_scrapy/middlewares.py#L62-L71)) records the requests in the _Request_-tab based on the response received.

```python
def process_response(self, request, response, spider):
    self.pipe_writer.write_request(
        url=response.url,
        status=response.status,
        method=request.method,
        rs=len(response.body),
        duration=request.meta.get('download_latency', 0) * 1000,
        parent=request.meta.setdefault(HS_PARENT_ID_KEY),
        fp=request_fingerprint(request),
    )
    ...
```

An option would be to update https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy to record the Requests based on processing the actual requests instead of responses. This seems quite straightforward though I'm not sure what's the reasoning of the original implementation.

**Comment by kmike** [comment]
> based on processing the actual requests instead of responses

Information includes "response size", so it seems it requires the response.

**Comment by Gallaecio** [comment]
We don’t need to make `scrapy-poet` a dependency, we only need to try to import from it, and don’t run the code if that did not work.

In the long run, the plan is not to have DummyResponse at all. Until that happens, I think modifying scrapinghub-entrypoint-scrapy may not be a bad idea.

**Comment by BurnzZ** [comment]
Having the following in https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/blob/master/sh_scrapy/middlewares.py#L62-L71 seems to be the easiest way indeed:

```python
    def process_response(self, request, response, spider):
        if type(response).__name__ == "DummyResponse":
            return response
        self.pipe_writer.write_request(...)
```

- No need to import **scrapy-poet**.
- I don't think the name `DummyResponse` would ever change. I also don't think it would be subclassed so having `isinstance()` checks won't be needed.

For the other approach, I'm not quite keen on the idea of passing a `"skip_for_scrapy_cloud_stats"` flag on the request-response pairs since it may get lost along the way _(e.g. some other middleware messed with it)_.

**Comment by PyExplorer** [comment]
Thanks @Gallaecio @BurnzZ! I'll test this approach then
```
def process_response(self, request, response, spider):
        if type(response).__name__ == "DummyResponse":
            return response
        self.pipe_writer.write_request(...)
```

**Comment by PyExplorer** [comment]
PR https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/pull/73

**Comment by Gallaecio** [comment]
Did https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/pull/73 fix this issue, or are there missing issues that need to be addressed here?

**Comment by BurnzZ** [comment]
I'm still seeing the same issue in my SC jobs this week. Perhaps the new https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy version with the fix was not deployed in all SC projects?

**Comment by Gallaecio** [comment]
Are you using stack 2.11?
