### ISSUE TITLE
Stat counter for page types requested

### ISSUE THREAD

**Issue by BurnzZ** [scrapy-plugins/scrapy-zyte-api#129]
In **scrapy-autoextract**, it was logging in the stats the types of requested pages ([code reference](https://github.com/scrapinghub/scrapy-autoextract/blob/e8b77703898ef3f8d29971d9cf1bdb5fde8fa0a6/scrapy_autoextract/providers.py#L241-L263)). For example:
```
autoextract/product/pages/count 4710
autoextract/product/pages/errors    28
autoextract/product/pages/success   4682
autoextract/productList/pages/count 290
autoextract/productList/pages/html  155
autoextract/productList/pages/success   290
```

It'd be nice if we could also track similar things in the stats for **scrapy-zyte-api**. We could include other things like `httpResponseBody`, `browserHtml`, etc.

The main **motivation** for this would be that during crawling, it'd be great to know what's the ratio between productNavigation and product pages which is useful for debugging the crawling behavior.

**Comment by Gallaecio** [comment]
We did add https://github.com/scrapy-plugins/scrapy-zyte-api/pull/128.

So it might be a matter of adding `/errors` and `/success` variants, and maybe change the current ones to `/count`.

**Comment by Gallaecio** [comment]
@BurnzZ Re-reading your request, I noticed that #128 should already cover your “motivation”. Do you still see value in the error-vs-success stats? I ask because doing those for all fields seems somewhat pointless. And I am also not sure what the criteria would be for error, e.g. same as for the entire request? probability?

**Comment by BurnzZ** [comment]
Yes, https://github.com/scrapy-plugins/scrapy-zyte-api/pull/128 covered most of it, cheers!

> Do you still see value in the error-vs-success stats?

Yes, as one of the issues faced in Zyte API currently are the errors like 520 and 521. It'd be great to see some stats like how many retries were done for a given data type extraction and how many have reached their max retries.

**Comment by Gallaecio** [comment]
We could implement a setting to define fields for which to log response status codes. Not sure if it should be empty by default, or include some main outputs (httpResponseBody, browserHtml, and extraction outputs).

**Comment by BurnzZ** [comment]
> We could implement a setting to define fields for which to log response status codes.

I think we could log everything by default since there's only a dozen of them, wherein only a few of them happen so often (e..g 200, 503, 520, 521)

**Comment by BurnzZ** [comment]
Hmmm I see the problem now. It could be confusing since the output params can be a mixture in the pool of requests. 

For example, `httpResponseBody ` would always go with another output like `httpResponseHeaders`. However, some requests with `httpResponseBody` could have `product` or `productNavigation` or no data type to extract at all. The stats have no way of denoting which combinations of output lead to errors and retries. I don't think it's also very useful to add at this point in the stats as having it in the logs is much more informative.

With that, I'm happy to close this one out. :)
