### ISSUE TITLE
Add JobPosting to the provider

### ISSUE THREAD

**Issue by wRAR** [scrapy-plugins/scrapy-zyte-api#158]
Comparing https://docs.zyte.com/zyte-api/usage/extract.html#zyte-api-extract-fields to https://scrapy-zyte-api.readthedocs.io/en/latest/reference/inputs.html#inputs I see `JobPosting` is missing, I think it should be trivial to add it or are there any problems?

**Comment by theumairahmed** [comment]
Hi folks, can this be prioritized? We have some spiders in DO using the old AutoExtract and we'd like to migrate them to ZyteAPI extraction.
