### ISSUE TITLE
Document that ZYTE_API_KEY can be set as an environment variable

### ISSUE THREAD

**Issue by Gallaecio** [scrapy-plugins/scrapy-zyte-api#18]

**Comment by BurnzZ** [comment]
I believe this has already been addressed in the current state of our README:

![image](https://user-images.githubusercontent.com/3449761/186668587-a10e62a9-d1a4-4f0e-ab55-743b45432aeb.png)

Shall we close this out? or is there something that needs to be further improved in the docs?

**Comment by Gallaecio** [comment]
Ah, I did not notice the code comment.
