### ISSUE TITLE
Using browser actions raises a TypeError

### ISSUE THREAD

**Issue by fcanobrash** [scrapy-plugins/scrapy-zyte-api#187]
Hi team.

Following the [example to use Browser Actions](https://scrapy-zyte-api.readthedocs.io/en/latest/usage/scrapy-poet.html#browser-actions), we're getting the following error:

`File ".../lib/python3.11/site-packages/scrapy_zyte_api/_annotations.py", line 62, in <genexpr>
    return tuple(frozenset(action.items()) for action in value)
TypeError: unhashable type: 'dict'`

We're using the same code from the documentation:

```
from typing import Annotated

from scrapy_zyte_api import Actions, actions


@attrs.define
class MyPageObject(BasePage):
    product: Product
    actions: Annotated[
        Actions,
        actions(
            [
                {
                    "action": "click",
                    "selector": {"type": "css", "value": "button#openDescription"},
                    "delay": 0,
                    "button": "left",
                    "onError": "return",
                },
                {
                    "action": "waitForTimeout",
                    "timeout": 5,
                    "onError": "return"
                },
            ]
        ),
    ]
```

**Comment by Gallaecio** [comment]
https://github.com/scrapy-plugins/scrapy-zyte-api/pull/188
