### ISSUE TITLE
Define a minimum Scrapy version

### ISSUE THREAD

**Issue by Gallaecio** [scrapy-plugins/scrapy-zyte-api#22]
We should indicate a minimum Scrapy version in the README.

I also wonder if Scrapy should be a dependency, `setup.py`-wise, so that the right version of Scrapy (or, more likely, the other way around) can be enforced during installation. [scrapy-zyte-smartproxy does it](/https://github.com/scrapy-plugins/scrapy-zyte-smartproxy/blob/master/setup.py#L38).

**Comment by BurnzZ** [comment]
I think we could perhaps set **2.6**, as the minimum as briefly discussed in https://github.com/scrapy-plugins/scrapy-zyte-api/pull/10#discussion_r883248928.

+1 on enforcing it in the `install_requires` param.
