### ISSUE TITLE
Log the actual request sent to Zyte API

### ISSUE THREAD

**Issue by Gallaecio** [scrapy-plugins/scrapy-zyte-api#48]
When requests go through Zyte API, it may be useful for debugging purposes to log exactly which parameters are sent to Zyte API (i.e. the JSON API request body).

This should become specially useful once we merge #41.

**Comment by kmike** [comment]
Do you propose to always log the exact requests, or to do it optionally? Any special logic for large requests (e.g. with large httpRequestBody)?

**Comment by Gallaecio** [comment]
> Do you propose to always log the exact requests, or to do it optionally?

It probably makes sense to make it opt-in with some setting. Otherwise, it would probably be too verbose by default.

> Any special logic for large requests (e.g. with large httpRequestBody)?

I had not though about it. Maybe we can set a length limit for that specific field, or for any field, and truncate them with an ellipsis when they surpass that length.
